config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :trips, except: [:index] do
    resources :photos
  end

  resources :users, except: [:index, :new] do 
    resources :trips, only: [:index]
  end
  get '/signup' => 'users#new'

  resources :searches, only: [:index]

  resources :sessions, only: [:create]
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/facebook", as: :sign_in_with_facebook
  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/:provider/callback/" => "callbacks#index"

end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user
  has_many :photos, dependent: :destroy

  #Geocoder
  geocoded_by :trip_location   
  after_validation :geocode, on: :create
  
  geocoded_by :trip_location, on: :update

  validates :title, presence: true,
                    uniqueness: { scope: :user_id },
                    length: { maximum: 50 }

  validates :country,
            :start_date,
            :end_date, presence: true

  validates :body, length: { maximum: 140 }


  def country_name
    country_iso = ISO3166::Country[country]
    country_iso.translations[I18n.locale.to_s] || country_iso.name
  end


  def trip_location
    city.nil? ? "#{country_name}" : "#{city} #{country_name}"
  end
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController

  before_action :find_trip, only: [:edit, :update, :destroy]

  def index
    @trips = current_user.trips.order(created_at: :desc)
    @trips_all = current_user.trips

    @geojson = Array.new
    geobuilder(@trips_all, current_user)
   
    respond_to do |format|
      format.html { render :index }
      format.js { render "return_map" }
      format.json { render json: @geojson }
    end

  end

  def new
    @trip = Trip.new

    respond_to do |format|
      format.html { render :index }
      format.js { render "success_trip" }
    end
  end

  def create
    @trips = current_user.trips
    @trip = Trip.new trip_params
    @trip.user = current_user

    respond_to do |format|
      if @trip.save
        format.html { render :index }
        format.js { render "success_trip_added" }
      else
        format.html { render :index }
        format.js { render "fail_trip" }
      end
    end
  end

  def edit

    respond_to do |format|
      format.js { render "success_edit" }
    end
  end

  def update
    respond_to do |format|
      if @trip.update trip_params
        format.js { render "success_trip_edited" }
      else
        format.js { render "fail_trip_edited" }
      end
    end 
  end

  def destroy
    @trip.destroy

    respond_to do |format|
      format.js { render "success_trip_deleted" }
    end
  end




  private

  def geobuilder(trips, user)
    trips.each do |trip|
      @geojson << {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates: [trip.longitude, trip.latitude]
        },
        properties: {
          title: trip.title,
          id: trip.id,
          url: trip_photos_url(trip.id),
          description: trip.trip_location,
          icon: {
              iconUrl: avatar(user), 
              iconSize: [40, 40], # size of the icon
              iconAnchor: [20, 20], # point of the icon which will correspond to marker's location
              popupAnchor: [0, -25], # point from which the popup should open relative to the iconAnchor
              className: "marker-icon"
              }
        }
      }
    end
  end


  def trip_params
    params.require(:trip).permit(:title, 
                                 :country, 
                                 :city, 
                                 :start_date, 
                                 :end_date, 
                                 :body)   
  end

  def find_trip
    @trip = Trip.find(params[:id])
  end

end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_edit_trip.html.erb
<div class="col s12 trip-form-container">
  <%= render 'trip_form' %>
</div>

app/views/trips/_map.html.erb
<div id="map" class="col s12">
  
</div>

<script>

  showMap();
  
  $('#map').hide().fadeIn(800, function(){
    map_box_obj.invalidateSize();
  });
</script>

app/views/trips/_new_trip.html.erb
<div class="col s12 trip-form-container">
  <%= form_for @trip, remote: true do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :title, "Title *" %>
        <%= f.text_field :title, length: 50, class: "validate" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= f.country_select :country, { include_blank: true } %>
        <%= f.label :country, "Country *" %>
      </div>
      <div class="input-field col s12 m6">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= f.label :start_date, class: "active" %>
        <%= f.date_field :start_date, class: "datepicker" %>
      </div>
      <div class="input-field col s12 m6">
        <%= f.label :end_date, class: "active" %>
        <%= f.date_field :end_date, class: "datepicker" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :body, "Trip Description" %>
        <%= f.text_area :body, class: "materialize-textarea", length: 140 %>
      </div>
    </div>
    <div class="col s12 center-align">
      <%= button_tag( class: "btn waves-effect waves-light" ) do %>
      Save Trip <i class='material-icons right'>send</i>
  <% end %>
</div>
  <% end %>
</div>

app/views/trips/_trip_form.html.erb
<%= form_for @trip, remote: true do |f| %>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :title, "Title *" %>
      <%= f.text_field :title, length: 50, class: "validate" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12 m6">
      <%= f.country_select :country, { include_blank: true } %>
      <%= f.label :country, "Country *" %>
    </div>
    <div class="input-field col s12 m6">
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12 m6">
      <%= f.label :start_date, class: "active" %>
      <%= f.date_field :start_date, class: "datepicker" %>
    </div>
    <div class="input-field col s12 m6">
      <%= f.label :end_date, class: "active" %>
      <%= f.date_field :end_date, class: "datepicker" %>
    </div>
  </div>
  <div class="row">
    <div class="input-field col s12">
      <%= f.label :body, "Trip Description" %>
      <%= f.text_area :body, class: "materialize-textarea", length: 140 %>
    </div>
  </div>
  <div class="col s12 center-align">
    <%= button_tag( class: "btn waves-effect waves-light" ) do %>
    Save Trip <i class='material-icons right'>send</i>
    <% end %>
  </div>
<% end %>

app/views/trips/_trips_list.html.erb
<li class="collection-item">
<a href="javascript:void(0)" class="trip-<%= trip.id %> trip-title"><%= trip.title %></a>
<%= link_to '<i class="zmdi zmdi-delete"></i>'.html_safe, trip_path(trip), remote: true, class: 'delete-trip-btn', method: :delete, data: {confirm: "Are you sure?"} %>
<%= link_to '<i class="zmdi zmdi-collection-image"></i>'.html_safe, new_trip_photo_path(trip), class: 'add-trip-photos-btn' %>
<%= link_to '<i class="zmdi zmdi-edit"></i>'.html_safe, edit_trip_path(trip), remote: true, class: 'edit-trip-btn' %>
</li>

app/views/trips/fail_trip.js.erb
$("#trips-right").html("<%= j render 'new_trip' %>");


var errorList = " <ul> <% @trip.errors.full_messages.each do |err| %> <li><%= err %></li> <% end %> </ul>"


Materialize.toast(errorList, 5000, 'rounded');


$('select').material_select();
$('input, textarea').characterCounter();
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });

app/views/trips/index.html.erb
<div class="container trips-container">

  <div class="row">
    <div id="trips-left" class="col s12 m4 center-align">
      <div>
        <%= link_to '<i class="zmdi zmdi-long-arrow-return"></i>'.html_safe, user_trips_path, remote: true, class: "return-trip-btn" %>
        <h5>My Trips</h5>
        <%= link_to '<i class="zmdi zmdi-collection-plus"></i>'.html_safe, new_trip_path, remote: true, class: "add-trip-btn" %>
      </div>
      <div class="row collection-row">
        <ul class="collection">
          <% @trips.each do |trip| %>
            <%= render partial: "trips_list", locals: { trip: trip } %>
          <% end %>
        </ul>
      </div>
    </div> <!--End col s5-->
    <div id="trips-right" class="col s12 m8">
      <%= render "map" %>
    </div>
  </div>
</div>

app/views/trips/new.html.erb
 
<div class="col s12 trip-form-container">
  <%= form_for @trip do |f| %>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :title %>
        <%= f.text_field :title %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= f.country_select :country, { include_blank: true } %>
        <%= f.label :country %>
      </div>
      <div class="input-field col s12 m6">
        <%= f.label :city %>
        <%= f.text_field :city %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12 m6">
        <%= f.label :start_date, class: "active" %>
        <%= f.date_field :start_date, class: "datepicker" %>
      </div>
      <div class="input-field col s12 m6">
        <%= f.label :end_date, class: "active" %>
        <%= f.date_field :end_date, class: "datepicker" %>
      </div>
    </div>
    <div class="row">
      <div class="input-field col s12">
        <%= f.label :body, "Trip" %>
        <%= f.text_area :body, class: "materialize-textarea", length: 140 %>
      </div>
    </div>
    <div class="col s12 center-align">
  <%= button_tag( :class => "btn waves-effect waves-light" ) do %>
    Save Trip <i class='material-icons right'>send</i>
  <% end %>
</div>
  <% end %>
</div>
 

app/views/trips/return_map.js.erb
$('#trips-right').html("<%= j render 'map' %>");

app/views/trips/success_edit.js.erb
$("#trips-right").html("<%= j render 'edit_trip' %>").hide().fadeIn(1000);


// Jquery required for the new trip form.
$('select').material_select();
$('input, textarea').characterCounter();
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });
Materialize.updateTextFields();

app/views/trips/success_trip.js.erb
$("#trips-right").html("<%= j render 'new_trip' %>").hide().fadeIn(2000);

// Jquery required for the new trip form.
$('select').material_select();
$('input, textarea').characterCounter();
$('.datepicker').pickadate({
    selectMonths: true, // Creates a dropdown to control month
    selectYears: 15 // Creates a dropdown of 15 years to control year
  });

app/views/trips/success_trip_added.js.erb
var newTrip = "<%= j render partial: 'trips_list', locals: { trip: @trip } %>";

$('#trips-left .collection').prepend(newTrip).hide().slideDown(700);

$('#trips-right').html("<%= j render 'map' %>");

app/views/trips/success_trip_deleted.js.erb
// Grag the current trip.id 
// Use the trip.id to find the edited trip in the list and remote it from the list
$tripId = <%= @trip.id %>
$('.collection .collection-item a.trip-' + $tripId ).parent().fadeOut(1000);

app/views/trips/success_trip_edited.js.erb
$('#trips-right').html("<%= j render 'map' %>");


// Grag the current trip.id 
// Use the trip.id to find the edited trip in the list and update it's title.
$tripId = <%= @trip.id %>
$('.collection .collection-item a.trip-' + $tripId ).fadeOut(400).html("<%= @trip.title %>").fadeIn(400);