config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :trips, except: [:index] do
    resources :photos
  end

  resources :users, except: [:index, :new] do 
    resources :trips, only: [:index]
  end
  get '/signup' => 'users#new'

  resources :searches, only: [:index]

  resources :sessions, only: [:create]
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/facebook", as: :sign_in_with_facebook
  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/:provider/callback/" => "callbacks#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  belongs_to :trip
  mount_uploader :trip_photo, TripPhotoUploader
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController

  def index
    @photos = current_trip.photos.all
    @photo = Photo.new
  end

  def new
    current_trip
    @photo = Photo.new

    respond_to do |format|
      format.html { render :new }
      format.js { render :js => "window.location.href='"+trip_photos_url(current_trip())+"'" }
      # format.js { render "success_photo_added" }
    end
  end

  def create
    @photos = current_trip.photos.all
    @photo = Photo.new photo_params
    @photo.trip_id = current_trip.id

    if @photo.save
      respond_to do |format|
        format.json{ render :json => @photo }
      end
    else
      render :new
    end
  end

  def edit

  end

  private

  def current_trip
    @trip = Trip.find(params[:trip_id])
  end

  def photo_params
    params.require(:photo).permit(:caption, :location, :trip_photo, :trip_photo_cache)
  end
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/photos/_add_photos.html.erb
<div class="row center-align">
    <%= link_to '<i class="zmdi zmdi-long-arrow-return"></i>'.html_safe, user_trips_path(current_user), class: "return-trip-index-btn" %>
    <span>
      <%= button_tag "Upload",id: "upload-btn", class: "btn waves-effect waves-light" %>
      <%= button_tag "Clear",id: "clear-btn", class: "btn waves-effect waves-light" %>
    </span>
  </div>

  <div class="row center-align">
    <div class="col s12 dropzone-container">
      <%= form_for [@trip, @photo], html: {id: 'trip-dropzone', class: 'dropzone'} do |f| %>
        <input name="authenticity_token" type="hidden" value="<%= form_authenticity_token %>" />
        <div class="dz-message needsclick">
          <h3>Drop files here</h3> or
          <strong>click</strong> to upload
        </div>
        <div class="fallback">
          <%= f.file_field :trip_photo, multiple: true%>
        </div>
      <% end %>
    </div>
  </div>

  <script>
  $(document).ready(function(){
    // disable auto discover
    Dropzone.autoDiscover = false;
   
    var dropzone = new Dropzone (".dropzone", {
      paramName: "photo[trip_photo]", // Rails expects the file upload to be something like model[field_name]
      addRemoveLinks: true, // Don't show remove links on dropzone itself.
      autoProcessQueue:false,
      maxFilesize: 2,

      init: function(){
        this.on("processing", function() {
          dropzone.options.autoProcessQueue = true;
        });

        this.on("queuecomplete", function(file) {
          // this.removeFile(file)
          $.getScript("<%= new_trip_photo_url %>")
        })
      }
    });

    $('#upload-btn').on('click',function(e){
      e.preventDefault();
      dropzone.processQueue();  
    }); 

    $('#clear-btn').on('click', function(){
      dropzone.removeAllFiles(true); 
    })

  });
  </script>

app/views/photos/_edit_photos.html.erb
<h1>Edit Files here</h1>

Render photos here to add caption/location

app/views/photos/_photo_fields.html.erb
<div class="row">
  <div class="input-field col s12">
    <%= f.label :caption %>
    <%= f.text_field :caption %>
  </div>
</div>
<div class-"row">
  <div class="input-field col s12">
    <%= f.label :location %>
    <%= f.text_field :location %>
  </div>
</div>

<div class="row">
  <div class="file-field input-field col s12">
    <div class="btn">
      <span>File</span>
      <%= f.file_field :trip_photo, :multiple => true %>
      <%= f.hidden_field :trip_photo_cache %>
    </div>
    <div class="file-path-wrapper">
      <%= text_field_tag :trip_photo, nil, class: "file-path validate" %>
    </div>
  </div>
  <%= link_to_remove_association "remove photo", f %>
</div>

app/views/photos/index.html.erb
<div class="container trips-photos-container">
  <%#= link_to "Add photo", new_trip_photo_path %>
  
  <div class="row">
    <div class="col s12">
      <div id="photo-gallery">
        <% @photos.each do |photo| %>
          <%= image_tag single_photo(photo), alt: photo.location, data: { image: photo.trip_photo.url, description: photo.caption } %>
        <% end %>
      </div>
    </div>
  </div>

</div>



<script>
  $(document).ready(function(){
    $("#photo-gallery").unitegallery({
      gallery_theme: "grid",
      theme_panel_position: "left",
      theme_hide_panel_under_width: 480,
      gallery_preserve_ratio: true,
      gallery_width: "100%",
      gallery_height: "calc(100vh - 64px)",
      gallery_control_thumbs_mousewheel: false,
      slider_control_zoom: false

    });
  });
</script>

app/views/photos/new.html.erb
<div class="container new-photos-container">

   <%= render "add_photos" %>

</div>

app/views/photos/success_photo_added.js.erb
$('.new-photos-container').html("hi");

console.log('fdf');