config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :trips, except: [:index] do
    resources :photos
  end

  resources :users, except: [:index, :new] do 
    resources :trips, only: [:index]
  end
  get '/signup' => 'users#new'

  resources :searches, only: [:index]

  resources :sessions, only: [:create]
  get '/login' => 'sessions#new'
  delete '/logout' => 'sessions#destroy'

  get "/auth/twitter", as: :sign_in_with_twitter
  get "/auth/facebook", as: :sign_in_with_facebook
  get "/auth/google_oauth2", as: :sign_in_with_google
  get "/auth/:provider/callback/" => "callbacks#index"

end

app/views/layouts/_side_user_menu.html.erb
<li><%= link_to "<i class='fa fa-camera-retro'></i> Explore".html_safe, searches_path %></li>
<li><%= link_to "<i class='zmdi zmdi-account-o zmdi-hc-fw'></i> Profile".html_safe, edit_user_path(current_user) %></li>
<li><%= link_to "<i class='zmdi zmdi-calendar-alt zmdi-hc-fw'></i> My Trips".html_safe, user_trips_path(current_user) %></li>
<li><%= link_to "<i class='zmdi zmdi-close zmdi-hc-fw'></i> Log Out".html_safe, logout_path, method: :delete %></li> 

app/views/layouts/_signup_menu.html.erb
<li><%= link_to "Sign Up", signup_path %></li>
<li><%= link_to "Login", login_path %></li>

app/views/layouts/_user_menu.html.erb
<li><%= link_to "<i class='zmdi zmdi-account-o zmdi-hc-fw'></i> Profile".html_safe, edit_user_path(current_user) %></li>
<li><%= link_to "<i class='zmdi zmdi-calendar-alt zmdi-hc-fw'></i> My Trips".html_safe, user_trips_path(current_user) %></li>
<li><%= link_to "<i class='zmdi zmdi-close zmdi-hc-fw'></i> Log Out".html_safe, logout_path, method: :delete %></li> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Peregrine</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!--Import Google Icon Font-->
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <!--Import materialize.css-->
  <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css"> -->
  
  <!--Import MD Iconic Font -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css">

  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

  <!-- MapBox-->
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.js'></script>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.2.4/mapbox.css' rel='stylesheet' />

  <% if user_signed_in? %>
    <meta name="current-user-id" content="<%= current_user.id %>"/>
  <% end %>
  
</head>


<body data-no-turbolink="true">
  
  <!-- Dropdown Structure -->
  <% if user_signed_in? %>
  <ul id="dropdown1" class="dropdown-content">
    <%= render "layouts/user_menu" %>
  </ul>
  <% end %>

  <nav>
    <div class="nav-wrapper">
      <a href="/" class="brand-logo center"> <%= image_tag 'logo.png' %> </a>
      <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
      <ul class="right hide-on-med-and-down">
        <!-- Dropdown Trigger -->
        <% if user_signed_in? %>
          <li>
            <%= link_to "<i class='fa fa-camera-retro'></i>".html_safe, searches_path %>
          </li>
          <li>
            <a class="dropdown-button" data-beloworigin="true" data-hover="true" href="#!" data-activates="dropdown1">
              <i class='material-icons left'>view_module</i><%= user_full_name %> <i class="material-icons right">arrow_drop_down</i>
            </a>
          </li>
        <% else %>
          <%= render "layouts/signup_menu" %>
        <% end %>
      </ul>
      <ul class="side-nav" id="mobile-demo">
        <% if user_signed_in? %>
          <%= render "layouts/side_user_menu" %>
        <% else %>
          <%= render "layouts/signup_menu" %>
        <% end %>
  
      </ul>
    </div>
  </nav>


<%= yield %>


  <!--Import jQuery before materialize.js-->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
</body>
</html>